before_script:
  - docker info
  - echo "$REGISTRY_PASSWORD" | docker login registry.gitlab.com -u "$REGISTRY_USER" --password-stdin

stages:
  - build
  - stop-old
  - deploy-new

build:
  stage: build
  only:
    - dev
  script:
    - IMG_TO_DEL=$(docker images registry.gitlab.com/wolfoxco/ikigai/authentication | grep 'latest' | awk '{ print $3}')
    - docker tag ${IMG_TO_DEL} authentication_to_del
    - docker build -t registry.gitlab.com/wolfoxco/ikigai/authentication .
    - docker push registry.gitlab.com/wolfoxco/ikigai/authentication
deploy-new:
  stage: deploy-new
  only:
    - dev
  script:
    - IMG_TO_RUN=$(docker images registry.gitlab.com/wolfoxco/ikigai/authentication | grep 'latest' | awk '{ print $3}')
    - NEW_INSTANCE=$(docker run -p 4262:8080 -e EXPOSED_PORT=4262 -e REGISTRY_HOST=172.17.0.1 -e DATABASE_URL=postgres://enterprises@172.17.0.1:5432 -e REGISTRY_PORT=4200 -d -t --restart unless-stopped ${IMG_TO_RUN})
    - docker rename ${NEW_INSTANCE} authentication
stop-old:
  stage: stop-old
  only:
    - dev
  script:
    - IMG_TO_DEL=$(docker images | grep 'authentication_to_del' | awk '{ print $3}')
    - CONTAINER_TO_STOP=$(docker ps | grep ${IMG_TO_DEL}  | awk '{ print $1}')
    - docker stop ${CONTAINER_TO_STOP}
    - docker rm ${CONTAINER_TO_STOP}
    - docker rmi ${IMG_TO_DEL} -f
