version: "3"

services:
  backend:
    image: node:lts-jessie
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: &auth ikigai_authentication
      PGDATABASE: *auth
    ports:
      - 9000:8080
    command: yarn dev
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: *auth
      POSTGRES_DB: *auth
